# Generated by Django 4.2.5 on 2023-09-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bscscan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="error_code",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="token_decimal",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="token_name",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="token_symbol",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(default=1, max_length=77),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="function_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="is_error",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="method_id",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="nonce",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="txreceipt_status",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
