# Generated by Django 4.2.5 on 2023-09-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bscscan", "0002_transaction_error_code_transaction_token_decimal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="block_number",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="confirmations",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="cumulative_gas_used",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="gas",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="gas_price",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="gas_used",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="nonce",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="token_decimal",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_index",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="value",
            field=models.BigIntegerField(),
        ),
    ]
