# Generated by Django 4.2.5 on 2023-09-06 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_address_user_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_number", models.IntegerField()),
                ("time_stamp", models.DateTimeField()),
                ("hash", models.CharField(max_length=77)),
                ("nonce", models.IntegerField()),
                ("block_hash", models.CharField(max_length=77)),
                ("transaction_index", models.IntegerField()),
                ("value", models.IntegerField()),
                ("gas", models.IntegerField()),
                ("gas_price", models.IntegerField()),
                ("is_error", models.BooleanField(default=True)),
                ("txreceipt_status", models.BooleanField(default=True)),
                ("input", models.TextField()),
                ("contract_address", models.TextField()),
                ("cumulative_gas_used", models.IntegerField()),
                ("gas_used", models.IntegerField()),
                ("confirmations", models.IntegerField()),
                ("method_id", models.CharField(max_length=70)),
                ("function_name", models.TextField()),
                (
                    "from_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_address",
                        to="base.address",
                    ),
                ),
                (
                    "to_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_address",
                        to="base.address",
                    ),
                ),
            ],
        ),
    ]
