# Generated by Django 4.2.5 on 2023-09-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
