# Generated by Django 4.2.5 on 2023-09-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bscscan", "__first__"),
        ("base", "0004_alter_address_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="from_address",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="to_address",
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.ManyToManyField(to="bscscan.address"),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
